script: bundle exec rspec spec
cache: bundler
language: ruby
rvm:
- 2.4.1
- 2.3.4
- jruby-9.1.2.0
addons:
  code_climate:
    repo_token:
      secure: EwSE5H3lIVnA0OlIZ4Qa3KE2bS6eCC458WNqMqgXEllf8FXU//vY2kynskRTQ3PsmO9q0k5LMxkeC5KXPf6nZjuITJ+4efiXL+BhLT50EMJo7OHQdR/sGptFdWl+oTBecWx26OISIfZVb4sVddxW19YDv5JjV5vI+GmBTUzpcdMzH3uwGIuIey/9Zh0wYpx8O/DGLjX0oWQl7nERgy3Rbcxth3u87pYrTn5o5nXqzQn35WoUGpa0MyqUHxAtWI8TqwSD5zCYi74SuVR3mnaj0QtJNAlPrSdzZ4E+mBzxJCvToRZtSlZmMhbt38ypoVLJ64a+lwtAQuWy6Yg924/AGVK2ovibnGSng9hefxYB2P8hTKYRNCwlfxIY66U0FwbI1yFMRlI+cAlMWkAGjZLwl/lZ9ky203vN+ReRcmq2Ryrzw/15yAE2UG+aKAO/WEJbd0DKTsmFPv+O7OVnQWboVv7QNaUcSCy9toicEEPAMlt8yRHe6NX+feNbDMCCzBN2dbZPofgVyYJk956s+Z+3CKZP9OUzYv6DD90SlHsBVsEIgkxh+0RN9twc7hLo42MVFFKy624o50QgFz6W4Tv3J1sRxuCr6kEg6YHkL8XD9Ovqe6XSoggHtDks1GmFIa0rreuwckRT4zYyw0NCkJJwbxKwr8SK+kjcNCLCDw2h708=
notifications:
  flowdock:
    secure: XHbGGBBN9XBMcAEr+NR1kzQUsLhXdolZ5hW0LIkf0oM1dkpPBrm7m3hKMZXq2OdwouUa0mgrt2Yz1T21mXX7bI//or92lVgWd/a1ptQcL/SN2j7/fN0PvD0KZWbY74poZU8I+hatKPXpVWGB5jsFlpROFAmTTvLz9T2XHNnQm91B7IQjbKRc/6p+2ZoW0avlsUgcUbtih5aitJj30xuwzVXVcaWb/bzuloMz5B3L3kw6tsgTzyJCr1x/BJBsxJQI8jVEzOtc09XNEbeQD9ZQl+7DRN51Q1iq1PiubpIgfNgpyTgqQvPp614T7yiPmvvypBkb6apN4BSJupaeWc8UTjroZvtUNCUQaefzYB/P3zXOS/ZGmXbD3Me3V5KTNpmZ5fx8MbUzTeU5iH4pVHvuf9oiVGah4vlDA2aUjk6PIxdAUVf7jE4/wbNYSi4TlH/DqBGBc1HB6M3/toVJ+BVqnZSfbOwpQOJv2ZY7OLI81uVmMgUyUeUKVxIjSb5YDhH7jh/cNS/FdHGCgMKKTLvJmNoIHKL8Y0dgH3bZWh7yzKpCpkkyXrqZSuAEtSD7Oc5u5QRZWtC9vfi61UFXBgyfbTh/nwgJ+OXZ2JyFjBgCPbs4EvH+0OZaPLFhpDNKTOs/aDHekdXnO0+SNPGxKb2w4Tb5GxKnK+Q2ZXOHETATMt8=
after_success:
  - bundle exec codeclimate-test-reporter
